# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 020ce86bb399ed5dcc2f00fe05f2de43818c42325a1adcf826a6e22e098a89f11b90c17e38896c9226470496c8bede1edf4f92213ad9bf91b17f33159cd85b7b

test:
  secret_key_base: e34c6f8a2c03c5705cf8dea107253b7edbd5693fb89b1e3f3169b50d0db86dfcd6107935835558929ffc9cc24597e3a4adebcb50fc702233ece7295b654e727a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
